# Generated by Django 3.1.4 on 2020-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=11)),
                ('image', models.URLField()),
            ],
        ),
    ]
